// <auto-generated />
using System;
using DAB_3_Solution_grp6.MSSQL.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAB_2_Solution_grp6.Api.Migrations
{
    [DbContext(typeof(CanteenAppDbContext))]
    [Migration("20230411121641_Migration3")]
    partial class Migration3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAB_2_Solution_grp6.DataAccess.Entities.Canteen", b =>
                {
                    b.Property<Guid>("CanteenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("CanteenId");

                    b.ToTable("Canteens");
                });

            modelBuilder.Entity("DAB_2_Solution_grp6.DataAccess.Entities.Customer", b =>
                {
                    b.Property<string>("AuId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DAB_2_Solution_grp6.DataAccess.Entities.Meal", b =>
                {
                    b.Property<Guid>("MealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CanteenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MealId");

                    b.HasIndex("CanteenId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("DAB_2_Solution_grp6.DataAccess.Entities.Menu", b =>
                {
                    b.Property<Guid>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CanteenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("StreetFoodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WarmDishName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MenuId");

                    b.HasIndex("CanteenId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("DAB_2_Solution_grp6.DataAccess.Entities.Rating", b =>
                {
                    b.Property<Guid>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("CanteenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Stars")
                        .HasPrecision(2, 1)
                        .HasColumnType("decimal(2,1)");

                    b.HasKey("RatingId");

                    b.HasIndex("AuId");

                    b.HasIndex("CanteenId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("DAB_2_Solution_grp6.DataAccess.Entities.Reservation", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("StreetQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("WarmQuantity")
                        .HasColumnType("int");

                    b.HasKey("ReservationId");

                    b.HasIndex("AuId");

                    b.HasIndex("MenuId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("DAB_2_Solution_grp6.DataAccess.Entities.Staff", b =>
                {
                    b.Property<Guid>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CanteenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StaffId");

                    b.HasIndex("CanteenId");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("DAB_2_Solution_grp6.DataAccess.Entities.Meal", b =>
                {
                    b.HasOne("DAB_2_Solution_grp6.DataAccess.Entities.Canteen", null)
                        .WithMany("Meals")
                        .HasForeignKey("CanteenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DAB_2_Solution_grp6.DataAccess.Entities.Reservation", null)
                        .WithMany("Meals")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DAB_2_Solution_grp6.DataAccess.Entities.Menu", b =>
                {
                    b.HasOne("DAB_2_Solution_grp6.DataAccess.Entities.Canteen", null)
                        .WithMany("Menus")
                        .HasForeignKey("CanteenId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAB_2_Solution_grp6.DataAccess.Entities.Rating", b =>
                {
                    b.HasOne("DAB_2_Solution_grp6.DataAccess.Entities.Customer", null)
                        .WithMany("Ratings")
                        .HasForeignKey("AuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DAB_2_Solution_grp6.DataAccess.Entities.Canteen", null)
                        .WithMany("Ratings")
                        .HasForeignKey("CanteenId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAB_2_Solution_grp6.DataAccess.Entities.Reservation", b =>
                {
                    b.HasOne("DAB_2_Solution_grp6.DataAccess.Entities.Customer", null)
                        .WithMany("Reservations")
                        .HasForeignKey("AuId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAB_2_Solution_grp6.DataAccess.Entities.Menu", null)
                        .WithMany("Reservations")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAB_2_Solution_grp6.DataAccess.Entities.Staff", b =>
                {
                    b.HasOne("DAB_2_Solution_grp6.DataAccess.Entities.Canteen", null)
                        .WithMany("Staff")
                        .HasForeignKey("CanteenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAB_2_Solution_grp6.DataAccess.Entities.Canteen", b =>
                {
                    b.Navigation("Meals");

                    b.Navigation("Menus");

                    b.Navigation("Ratings");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DAB_2_Solution_grp6.DataAccess.Entities.Customer", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("DAB_2_Solution_grp6.DataAccess.Entities.Menu", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("DAB_2_Solution_grp6.DataAccess.Entities.Reservation", b =>
                {
                    b.Navigation("Meals");
                });
#pragma warning restore 612, 618
        }
    }
}
